/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengguna.view;

import common.controller.TextFieldOptions;
import common.model.PesanDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import pengguna.controller.PembayaranController;
import pengguna.controller.TransaksiController;

/**
 *
 * @author WILDAN
 */
public class FormBayar extends javax.swing.JDialog {
    
    private String kd_transaksi;
    private String nip;
    private final PembayaranController pembayaranController = new PembayaranController();
    private PesanDialog pesanDialog = new PesanDialog();
    private JTable tableTransaksi;
    private final TransaksiController transaksiController = new TransaksiController();
    /**
     * Creates new form FormBayar
     */
    public FormBayar(java.awt.Frame parent, boolean modal, JTable tableTransaksi,
            String kd_transaksi, String nip, String status) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        radioDp.setActionCommand("DP");
        radioLunas.setActionCommand("Lunas");
        radioDp.setSelected(true);
        this.kd_transaksi = kd_transaksi;
        this.nip = nip;
        this.tableTransaksi = tableTransaksi;
        TextFieldOptions.harga(txtJumlahBayar);
        pembayaranController.setKode(txtKodePembayaran);
        pembayaranController.initTrx(kd_transaksi, status, txtKodeTrx, txtInstansi, txtPenanggungJawab,txtTotalBiaya, txtSisaTagihan, txtJumlahBayar, btnCetakdanBayar, statusGroup);
        pembayaranController.readData(tablePembayaran, kd_transaksi,this);
        
    }
    
    private void setJumlahBayar(String actionCommand){
        if(actionCommand.equals("Lunas")){
            txtJumlahBayar.setText(txtSisaTagihan.getText());
        }else{
            txtJumlahBayar.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusGroup = new javax.swing.ButtonGroup();
        btnCetakdanBayar = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePembayaran = new javax.swing.JTable();
        txtKodeTrx = new javax.swing.JTextField();
        txtInstansi = new javax.swing.JTextField();
        txtSisaTagihan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        radioLunas = new javax.swing.JRadioButton();
        radioDp = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtJumlahBayar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPenanggungJawab = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtKodePembayaran = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTotalBiaya = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnCetakdanBayar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCetakdanBayar.setText("Cetak & Bayar");
        btnCetakdanBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakdanBayarActionPerformed(evt);
            }
        });

        btnBatal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBatal.setText("Batal");

        tablePembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cetak", "Kode Bayar", "Status Bayar", "Jumlah Bayar", "Tanggal Bayar", "Penerima"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePembayaran);

        txtKodeTrx.setEditable(false);
        txtKodeTrx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtInstansi.setEditable(false);
        txtInstansi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSisaTagihan.setEditable(false);
        txtSisaTagihan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSisaTagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSisaTagihanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kode Transaksi");

        statusGroup.add(radioLunas);
        radioLunas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioLunas.setText("Lunas");
        radioLunas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLunasActionPerformed(evt);
            }
        });

        statusGroup.add(radioDp);
        radioDp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        radioDp.setText("DP");
        radioDp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDpActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Instansi");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Sisa Tagihan");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Jumlah Bayar");

        txtJumlahBayar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tipe Bayar");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Penanggung Jawab");

        txtPenanggungJawab.setEditable(false);
        txtPenanggungJawab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Daftar Pembayaran");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Pembayaran");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Kode Pembayaran");

        txtKodePembayaran.setEditable(false);
        txtKodePembayaran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Total Biaya");

        txtTotalBiaya.setEditable(false);
        txtTotalBiaya.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTotalBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalBiayaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPenanggungJawab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtInstansi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                        .addComponent(txtKodeTrx, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtKodePembayaran, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(34, 34, 34)
                                        .addComponent(radioDp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radioLunas))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel10))
                                                .addGap(25, 25, 25))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtSisaTagihan, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                                .addComponent(txtTotalBiaya))
                                            .addComponent(txtJumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(323, 323, 323)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(btnCetakdanBayar)
                                .addGap(18, 18, 18)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 33, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKodePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtKodeTrx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInstansi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPenanggungJawab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioDp)
                            .addComponent(radioLunas)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSisaTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(txtJumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCetakdanBayar)
                    .addComponent(btnBatal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakdanBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakdanBayarActionPerformed
        // TODO add your handling code here:
        if(pesanDialog.tampilkanPilihan("Apakah detail pembayaran sudah benar?", "Konfirmasi", new Object[]{"Ya","Tidak"}) == 0){
            if(pembayaranController.simpan("tambah",txtKodePembayaran, txtKodeTrx, txtJumlahBayar,txtTotalBiaya, txtSisaTagihan, statusGroup, nip)){
                JOptionPane.showMessageDialog(null, "Pembayaran Berhasil!");
                pembayaranController.cetakStruk(txtKodePembayaran.getText());
                if(pesanDialog.tampilkanPilihan("Apakah anda ingin melanjutkan pembayaran pada transaksi ini?", "Konfirmasi", new Object[]{"Ya","Tidak"}) == 1){
                    pembayaranController.readData(tablePembayaran, kd_transaksi, this);
                    dispose();
                }
            }
               
        }
    }//GEN-LAST:event_btnCetakdanBayarActionPerformed

    private void radioDpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDpActionPerformed
        // TODO add your handling code here:
        setJumlahBayar(evt.getActionCommand());
    }//GEN-LAST:event_radioDpActionPerformed

    private void radioLunasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLunasActionPerformed
        // TODO add your handling code here:
         setJumlahBayar(evt.getActionCommand());
    }//GEN-LAST:event_radioLunasActionPerformed

    private void txtSisaTagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSisaTagihanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSisaTagihanActionPerformed

    private void txtTotalBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalBiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalBiayaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        transaksiController.readData(tableTransaksi);
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCetakdanBayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioDp;
    private javax.swing.JRadioButton radioLunas;
    private javax.swing.ButtonGroup statusGroup;
    private javax.swing.JTable tablePembayaran;
    private javax.swing.JTextField txtInstansi;
    private javax.swing.JTextField txtJumlahBayar;
    private javax.swing.JTextField txtKodePembayaran;
    private javax.swing.JTextField txtKodeTrx;
    private javax.swing.JTextField txtPenanggungJawab;
    private javax.swing.JTextField txtSisaTagihan;
    private javax.swing.JTextField txtTotalBiaya;
    // End of variables declaration//GEN-END:variables
}
