/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengguna.view;

import common.controller.ActivityController;
import common.controller.TextFieldOptions;
import com.toedter.calendar.JTextFieldDateEditor;
import common.controller.LoginController;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;
import pengguna.controller.CalculateController;
import pengguna.controller.TransaksiController;
import common.model.Fasilitas;
import common.model.Golongan;
import common.model.PesanDialog;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import pengguna.controller.InstansiController;

/**
 *
 * @author WILDAN
 */
public class FormTambahTransaksi extends javax.swing.JDialog {
    private final TransaksiController transaksiController = new TransaksiController();
    private final InstansiController instansiController = new InstansiController();
    private FormPilihFasilitas pilihFasilitas;
    private FormPilihGolongan pilihGolongan;
    private FormBayar formBayar;
    JTextFieldDateEditor editor1, editor2;
    JTable tableTransaksi;
    JToggleButton toggleTambah;
    ArrayList<Fasilitas> listFasilitas = new ArrayList<>();
    ArrayList<Golongan> listGolongan = new ArrayList<>();
    long diff;
    int days = 0;
    Date awal = null;
    Date akhir = null;
    private String nip = "";
    CalculateController calculateController = new CalculateController();
    PesanDialog pesanDialog = new PesanDialog();
    
    /**
     * Creates new form FormTambahPengguna
     */
    public FormTambahTransaksi(java.awt.Frame parent, boolean modal, 
            JToggleButton toggleTambah, 
            JTable tableTransaksi, String nip) {
        super(parent, modal);
        this.toggleTambah = toggleTambah;
        this.tableTransaksi = tableTransaksi;
        this.nip = nip;
        initComponents();
        editor1 = (JTextFieldDateEditor) dateAwal.getDateEditor();
        editor1.setEditable(false);
        editor2 = (JTextFieldDateEditor) dateAkhir.getDateEditor();
        editor2.setEditable(false);
        setLocationRelativeTo(null);
        transaksiController.setKode(txtKodeTransaksi);
       
        TextFieldOptions.phoneNumber(txtTeleponInstansi);
        dateAwal.setDate(new Date());
        dateAkhir.setDate(new Date());
        txtChanged(txtTotalFasilitas);
        txtChanged(txtTotalGolongan);
        dateAwal.setMinSelectableDate(new Date());
        dateAkhir.setMinSelectableDate(new Date());
        transaksiController.setDateChooser(dateAwal);
        transaksiController.setDateChooser(dateAkhir);
    }
    
    private void clear(){
        transaksiController.setKode(txtKodeTransaksi);
        txtInstansi.setText("");
        txtJumlahPeserta.setText("");
        txtAreaAlamatInstansi.setText("");
        editor1.setText("");
        editor2.setText("");
        txtTeleponInstansi.setText("");
        txtEmail.setText("");
    }
    
    private void txtChanged(JTextField txtField){
        txtField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
              calculateController.hitungTotal(days,listFasilitas, listGolongan, txtTotalTagihan);
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
              calculateController.hitungTotal(days,listFasilitas, listGolongan, txtTotalTagihan);
            }
            @Override
            public void insertUpdate(DocumentEvent e) {
              calculateController.hitungTotal(days, listFasilitas, listGolongan, txtTotalTagihan);
            }
          });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkGroupRadio = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtKodeTransaksi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtInstansi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtJumlahPeserta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        dateAwal = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtTeleponInstansi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaAlamatInstansi = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnBersih = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dateAkhir = new com.toedter.calendar.JDateChooser();
        btnPilihFasilitas = new javax.swing.JButton();
        btnPilihGolongan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtPenanggungJawab = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTotalTagihan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFasilitas = new javax.swing.JTable();
        txtTotalFasilitas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTotalGolongan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableGolongan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Tambah Transaksi");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kode Transaksi");

        txtKodeTransaksi.setEditable(false);
        txtKodeTransaksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Instansi");

        txtInstansi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Penanggung Jawab");

        txtJumlahPeserta.setEditable(false);
        txtJumlahPeserta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("No Telpon Instansi");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Email");

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dateAwal.setDateFormatString("yyyy/MM/dd");
        dateAwal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateAwal.setMaxSelectableDate(new java.util.Date(1735668109000L));
        dateAwal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateAwalPropertyChange(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tanggal Awal");

        txtTeleponInstansi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Alamat Instansi");

        txtAreaAlamatInstansi.setColumns(20);
        txtAreaAlamatInstansi.setRows(5);
        jScrollPane1.setViewportView(txtAreaAlamatInstansi);

        btnSimpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBersih.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBersih.setText("Bersihkan");
        btnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Transaksi Penyewaan");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Tanggal Akhir");

        dateAkhir.setDateFormatString("yyyy/MM/dd");
        dateAkhir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateAkhir.setMaxSelectableDate(new java.util.Date(1735668109000L));
        dateAkhir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateAkhirPropertyChange(evt);
            }
        });

        btnPilihFasilitas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPilihFasilitas.setText("Pilih Fasilitas");
        btnPilihFasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihFasilitasActionPerformed(evt);
            }
        });

        btnPilihGolongan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPilihGolongan.setText("Pilih Golongan");
        btnPilihGolongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihGolonganActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Jumlah Peserta");

        txtPenanggungJawab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Orang");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel14.setText("Total Tagihan");

        txtTotalTagihan.setEditable(false);
        txtTotalTagihan.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtTotalTagihan.setText("0");

        tableFasilitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Fasilitas", "Harga", "Status", "Jumlah", "Total Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFasilitas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tableFasilitasPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tableFasilitas);
        if (tableFasilitas.getColumnModel().getColumnCount() > 0) {
            tableFasilitas.getColumnModel().getColumn(0).setPreferredWidth(5);
            tableFasilitas.getColumnModel().getColumn(1).setPreferredWidth(120);
            tableFasilitas.getColumnModel().getColumn(3).setPreferredWidth(20);
            tableFasilitas.getColumnModel().getColumn(4).setPreferredWidth(35);
        }

        txtTotalFasilitas.setEditable(false);
        txtTotalFasilitas.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtTotalFasilitas.setText("0");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel15.setText("Total");

        txtTotalGolongan.setEditable(false);
        txtTotalGolongan.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtTotalGolongan.setText("0");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel16.setText("Total");

        tableGolongan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Golongan", "Harga", "Peserta", "Panitia", "Pembina", "Total Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableGolongan);
        if (tableGolongan.getColumnModel().getColumnCount() > 0) {
            tableGolongan.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableGolongan.getColumnModel().getColumn(1).setPreferredWidth(50);
            tableGolongan.getColumnModel().getColumn(3).setPreferredWidth(35);
            tableGolongan.getColumnModel().getColumn(4).setPreferredWidth(35);
            tableGolongan.getColumnModel().getColumn(5).setPreferredWidth(35);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnPilihFasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPilihGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(347, 347, 347))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(460, 460, 460)
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(txtJumlahPeserta, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel13)
                            .addGap(169, 169, 169))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtKodeTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtInstansi, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTeleponInstansi, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPenanggungJawab, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel6)))
                                .addComponent(jLabel9))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(dateAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(101, 101, 101)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(327, 327, 327))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(383, 383, 383))))
            .addGroup(layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBersih, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalFasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(515, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKodeTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInstansi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPenanggungJawab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTeleponInstansi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtJumlahPeserta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTotalTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPilihGolongan)
                    .addComponent(btnPilihFasilitas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalFasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtTotalGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBersih))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(412, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(113, 113, 113)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(pesanDialog.tampilkanPilihan("Apakah detail transaksi penyewaan sudah benar?", "Konfirmasi", new Object[]{"Ya","Tidak"}) == 0){
            if(instansiController.simpan("tambah", txtInstansi, txtPenanggungJawab, txtTeleponInstansi, txtEmail, txtAreaAlamatInstansi,instansiController.getKodeInstansi(), listGolongan)){
                if(transaksiController.simpan("tambah", txtKodeTransaksi, editor1, editor2, txtTotalTagihan, txtJumlahPeserta, "Sewa", instansiController.getKodeInstansi(), listFasilitas, nip)){
                    JOptionPane.showMessageDialog(null, "Transaksi Berhasil!");
                    formBayar = new FormBayar(null,true,tableTransaksi,txtKodeTransaksi.getText(), nip, "Proses");
                    formBayar.setVisible(true);
                    dispose();
                    clear();
                }
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        toggleTambah.setSelected(false);
        clear();
        transaksiController.readData(tableTransaksi);
    }//GEN-LAST:event_formWindowClosed

    private void btnPilihFasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihFasilitasActionPerformed
        // TODO add your handling code here:
        listFasilitas = new ArrayList<>();
        pilihFasilitas = new FormPilihFasilitas(null, true, tableFasilitas, listFasilitas, txtTotalFasilitas, days);
        pilihFasilitas.setVisible(true);
    }//GEN-LAST:event_btnPilihFasilitasActionPerformed

    private void btnPilihGolonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihGolonganActionPerformed
        // TODO add your handling code here:
        listGolongan = new ArrayList<>();
        pilihGolongan = new FormPilihGolongan(null, true, tableGolongan, listGolongan, txtJumlahPeserta, txtTotalGolongan, days);
        pilihGolongan.setVisible(true);
    }//GEN-LAST:event_btnPilihGolonganActionPerformed

    private void dateAwalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateAwalPropertyChange
        // TODO add your handling code here:
        if("date".equals(evt.getPropertyName())){
            awal = (Date) evt.getNewValue();
            dateAkhir.setMinSelectableDate(awal);
        }
    }//GEN-LAST:event_dateAwalPropertyChange

    private void dateAkhirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateAkhirPropertyChange
        // TODO add your handling code here:
        if(awal != null){
            if("date".equals(evt.getPropertyName())){
                akhir = (Date) evt.getNewValue();
                diff = akhir.getTime() - awal.getTime();
                days = (int)(diff / (1000*60*60*24))+1;
                calculateController.hitungTotal(days, listFasilitas, listGolongan, txtTotalTagihan);
            }
        }
    }//GEN-LAST:event_dateAkhirPropertyChange

    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnBersihActionPerformed

    private void tableFasilitasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tableFasilitasPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tableFasilitasPropertyChange

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersih;
    private javax.swing.JButton btnPilihFasilitas;
    private javax.swing.JButton btnPilihGolongan;
    private javax.swing.JButton btnSimpan;
    private com.toedter.calendar.JDateChooser dateAkhir;
    private com.toedter.calendar.JDateChooser dateAwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.ButtonGroup jkGroupRadio;
    private javax.swing.JTable tableFasilitas;
    private javax.swing.JTable tableGolongan;
    private javax.swing.JTextArea txtAreaAlamatInstansi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtInstansi;
    private javax.swing.JTextField txtJumlahPeserta;
    private javax.swing.JTextField txtKodeTransaksi;
    private javax.swing.JTextField txtPenanggungJawab;
    private javax.swing.JTextField txtTeleponInstansi;
    private javax.swing.JTextField txtTotalFasilitas;
    private javax.swing.JTextField txtTotalGolongan;
    private javax.swing.JTextField txtTotalTagihan;
    // End of variables declaration//GEN-END:variables
}
