/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengguna.view;

import common.controller.ActivityController;
import common.controller.TextFieldOptions;
import com.toedter.calendar.JTextFieldDateEditor;
import common.controller.LoginController;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableModel;
import pengguna.controller.CalculateController;
import pengguna.controller.TransaksiController;
import common.model.Fasilitas;
import common.model.Golongan;
import common.model.PesanDialog;
import common.model.UserLogin;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import pengguna.controller.InstansiController;

/**
 *
 * @author WILDAN
 */
public class FormDetailTransaksi extends javax.swing.JDialog {
    private final TransaksiController transaksiController = new TransaksiController();
    private final InstansiController instansiController = new InstansiController();
    private final LoginController loginController = new LoginController();
    private FormBayar formBayar;
    private FormPilihFasilitas pilihFasilitas;
    private FormPilihGolongan pilihGolongan;
    JTextFieldDateEditor editor1, editor2;
    JTable tableTransaksi;
    ArrayList<Fasilitas> listFasilitas = new ArrayList<>();
    ArrayList<Golongan> listGolongan = new ArrayList<>();
    long diff;
    int days = 0;
    Date awal = null;
    Date akhir = null;
    String kd_transaksi;
    String kd_instansi;
    CalculateController calculateController = new CalculateController();
    PesanDialog pesanDialog = new PesanDialog();
    /**
     * Creates new form FormTambahPengguna
     */
    public FormDetailTransaksi(java.awt.Frame parent, boolean modal, 
            JTable tableTransaksi, String kd_transaksi, String kd_instansi, String status) {
        super(parent, modal);
        this.tableTransaksi = tableTransaksi;
        this.kd_transaksi = kd_transaksi;
        this.kd_instansi = kd_instansi;
        initComponents();
        
        transaksiController.bacaSingle(kd_transaksi, txtKodeTransaksi, txtInstansi, txtPenanggungJawab, txtEmail, txtTeleponInstansi, txtAreaAlamatInstansi, tableFasilitas,txtTotalFasilitas, tableGolongan,txtTotalGolongan, dateAwal, dateAkhir, txtJumlahPeserta, txtTotalTagihan, this.listFasilitas, this.listGolongan);
        editor1 = (JTextFieldDateEditor) dateAwal.getDateEditor();
        editor1.setEditable(false);
        editor2 = (JTextFieldDateEditor) dateAkhir.getDateEditor();
        editor2.setEditable(false);
        setLocationRelativeTo(null);
        txtChanged(txtTotalFasilitas);
        txtChanged(txtTotalGolongan);
        TextFieldOptions.phoneNumber(txtTeleponInstansi);
        dateAwal.setMinSelectableDate(new Date());
        dateAkhir.setMinSelectableDate(new Date());
        if(!status.equalsIgnoreCase("Proses")){
            btnSimpan.setEnabled(false);
        }
    }
    
    public void setDateEvaluator(){
        
    }
    
    private void clear(){
        transaksiController.setKode(txtKodeTransaksi);
        txtInstansi.setText("");
        txtJumlahPeserta.setText("");
        txtAreaAlamatInstansi.setText("");
        editor1.setText("");
        editor2.setText("");
        txtTeleponInstansi.setText("");
        txtEmail.setText("");
    }
    
    private void txtChanged(JTextField txtField){
        txtField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
              calculateController.hitungTotal( days, listFasilitas, listGolongan, txtTotalTagihan);
            }
            @Override
            public void removeUpdate(DocumentEvent e) {
              calculateController.hitungTotal( days, listFasilitas, listGolongan, txtTotalTagihan);
            }
            @Override
            public void insertUpdate(DocumentEvent e) {
              calculateController.hitungTotal( days, listFasilitas, listGolongan, txtTotalTagihan);
            }
          });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jkGroupRadio = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtKodeTransaksi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtInstansi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtJumlahPeserta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        dateAwal = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        txtTeleponInstansi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaAlamatInstansi = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnBersih = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dateAkhir = new com.toedter.calendar.JDateChooser();
        btnPilihFasilitas = new javax.swing.JButton();
        btnPilihGolongan = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtPenanggungJawab = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTotalTagihan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFasilitas = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableGolongan = new javax.swing.JTable();
        txtTotalFasilitas = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTotalGolongan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Detail Transaksi");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Kode Transaksi");

        txtKodeTransaksi.setEditable(false);
        txtKodeTransaksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Instansi");

        txtInstansi.setEditable(false);
        txtInstansi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Penanggung Jawab");

        txtJumlahPeserta.setEditable(false);
        txtJumlahPeserta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("No Telpon Instansi");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Email");

        txtEmail.setEditable(false);
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        dateAwal.setDateFormatString("yyyy/MM/dd");
        dateAwal.setEnabled(false);
        dateAwal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateAwal.setMaxSelectableDate(new java.util.Date(1735668109000L));
        dateAwal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateAwalPropertyChange(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tanggal Awal");

        txtTeleponInstansi.setEditable(false);
        txtTeleponInstansi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Alamat Instansi");

        txtAreaAlamatInstansi.setEditable(false);
        txtAreaAlamatInstansi.setColumns(20);
        txtAreaAlamatInstansi.setRows(5);
        jScrollPane1.setViewportView(txtAreaAlamatInstansi);

        btnSimpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSimpan.setText("Update");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBersih.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBersih.setText("Bersihkan");
        btnBersih.setEnabled(false);
        btnBersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Detail Transaksi");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Tanggal Akhir");

        dateAkhir.setDateFormatString("yyyy/MM/dd");
        dateAkhir.setEnabled(false);
        dateAkhir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateAkhir.setMaxSelectableDate(new java.util.Date(1735668109000L));
        dateAkhir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateAkhirPropertyChange(evt);
            }
        });

        btnPilihFasilitas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPilihFasilitas.setText("Pilih Fasilitas");
        btnPilihFasilitas.setEnabled(false);
        btnPilihFasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihFasilitasActionPerformed(evt);
            }
        });

        btnPilihGolongan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPilihGolongan.setText("Pilih Golongan");
        btnPilihGolongan.setEnabled(false);
        btnPilihGolongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihGolonganActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Jumlah Peserta");

        txtPenanggungJawab.setEditable(false);
        txtPenanggungJawab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Orang");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel14.setText("Total Tagihan");

        txtTotalTagihan.setEditable(false);
        txtTotalTagihan.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtTotalTagihan.setText("0");

        tableFasilitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Fasilitas", "Harga", "Status", "Jumlah", "Total Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableFasilitas);
        if (tableFasilitas.getColumnModel().getColumnCount() > 0) {
            tableFasilitas.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableFasilitas.getColumnModel().getColumn(1).setPreferredWidth(100);
            tableFasilitas.getColumnModel().getColumn(2).setPreferredWidth(50);
            tableFasilitas.getColumnModel().getColumn(3).setPreferredWidth(50);
            tableFasilitas.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        tableGolongan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Golongan", "Harga", "Peserta", "Panitia", "Pembina", "Total Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableGolongan);
        if (tableGolongan.getColumnModel().getColumnCount() > 0) {
            tableGolongan.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableGolongan.getColumnModel().getColumn(3).setPreferredWidth(35);
            tableGolongan.getColumnModel().getColumn(4).setPreferredWidth(35);
            tableGolongan.getColumnModel().getColumn(5).setPreferredWidth(35);
        }

        txtTotalFasilitas.setEditable(false);
        txtTotalFasilitas.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtTotalFasilitas.setText("0");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel15.setText("Total");

        txtTotalGolongan.setEditable(false);
        txtTotalGolongan.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtTotalGolongan.setText("0");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel16.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnPilihFasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalFasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPilihGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(335, 335, 335))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txtTotalTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtKodeTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtInstansi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTeleponInstansi, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPenanggungJawab, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel6))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dateAkhir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dateAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtJumlahPeserta, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)))))
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(382, 382, 382)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBersih, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateAkhir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKodeTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInstansi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPenanggungJawab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTeleponInstansi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtJumlahPeserta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTotalTagihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPilihGolongan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPilihFasilitas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalFasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBersih))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(btnSimpan.getText().equalsIgnoreCase("update")){
            btnSimpan.setText("Simpan");
            dateAwal.setEnabled(true);
            dateAkhir.setEnabled(true);
            btnPilihFasilitas.setEnabled(true);
            btnPilihGolongan.setEnabled(true);
        }else{
            if(pesanDialog.tampilkanPilihan("Apakah detail transaksi penyewaan sudah benar?", "Konfirmasi", new Object[]{"Ya","Tidak"}) == 0){
                if(instansiController.simpan("update", txtInstansi, txtPenanggungJawab, txtTeleponInstansi, txtEmail, txtAreaAlamatInstansi, kd_instansi, listGolongan)){
                    if(transaksiController.simpan("update", txtKodeTransaksi, editor1, editor2, txtTotalTagihan, txtJumlahPeserta, "Sewa", kd_instansi, listFasilitas, UserLogin.getNip())){
                        JOptionPane.showMessageDialog(null, "Transaksi Berhasil!");
                        dispose();
                        clear();
                    }
                }
            }
        }
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnBersihActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        clear();
        transaksiController.readData(tableTransaksi);
    }//GEN-LAST:event_formWindowClosed

    private void btnPilihFasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihFasilitasActionPerformed
        // TODO add your handling code here:
        listFasilitas = new ArrayList<>();
        pilihFasilitas = new FormPilihFasilitas(null, true, tableFasilitas, listFasilitas, txtTotalFasilitas, days);
        pilihFasilitas.setVisible(true);
    }//GEN-LAST:event_btnPilihFasilitasActionPerformed

    private void btnPilihGolonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihGolonganActionPerformed
        // TODO add your handling code here:
        listGolongan = new ArrayList<>();
        pilihGolongan = new FormPilihGolongan(null, true, tableGolongan, listGolongan, txtJumlahPeserta, txtTotalGolongan, days);
        pilihGolongan.setVisible(true);
    }//GEN-LAST:event_btnPilihGolonganActionPerformed

    private void dateAwalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateAwalPropertyChange
        // TODO add your handling code here:
        if("date".equals(evt.getPropertyName())){
            awal = (Date) evt.getNewValue();
            dateAkhir.setMinSelectableDate(awal);
        }
    }//GEN-LAST:event_dateAwalPropertyChange

    private void dateAkhirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateAkhirPropertyChange
        // TODO add your handling code here:
        if(awal != null){
            if("date".equals(evt.getPropertyName())){
                akhir = (Date) evt.getNewValue();
                diff = akhir.getTime() - awal.getTime();
                days = (int)(diff / (1000*60*60*24))+1;
                calculateController.hitungTotal(days, listFasilitas, listGolongan, txtTotalTagihan);
            }
        }
        
        
    }//GEN-LAST:event_dateAkhirPropertyChange

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBersih;
    private javax.swing.JButton btnPilihFasilitas;
    private javax.swing.JButton btnPilihGolongan;
    private javax.swing.JButton btnSimpan;
    private com.toedter.calendar.JDateChooser dateAkhir;
    private com.toedter.calendar.JDateChooser dateAwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.ButtonGroup jkGroupRadio;
    private javax.swing.JTable tableFasilitas;
    private javax.swing.JTable tableGolongan;
    private javax.swing.JTextArea txtAreaAlamatInstansi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtInstansi;
    private javax.swing.JTextField txtJumlahPeserta;
    private javax.swing.JTextField txtKodeTransaksi;
    private javax.swing.JTextField txtPenanggungJawab;
    private javax.swing.JTextField txtTeleponInstansi;
    private javax.swing.JTextField txtTotalFasilitas;
    private javax.swing.JTextField txtTotalGolongan;
    private javax.swing.JTextField txtTotalTagihan;
    // End of variables declaration//GEN-END:variables
}
