/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengguna.view;

import java.util.ArrayList;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import pengguna.controller.FasilitasController;
import common.model.Fasilitas;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author WILDAN
 */
public class FormPilihFasilitas extends javax.swing.JDialog {
    private final FasilitasController fasilitasController = new FasilitasController();
    DefaultTableModel model;
    ArrayList<Fasilitas> listFasilitas;
    JTextField txtTotalFasilitas;
    JTable tableFas;
    NumberFormat format = NumberFormat.getNumberInstance(new Locale("in", "ID"));
    int days;
    /**
     * Creates new form FormPilihFasilitas
     */
    public FormPilihFasilitas(java.awt.Frame parent, boolean modal, 
            JTable tableFas, 
            ArrayList<Fasilitas> listFasilitas, JTextField txtTotalFasilitas, int days) {
        super(parent, modal);
        initComponents();
        this.listFasilitas = listFasilitas;
        this.tableFas = tableFas;
        this.txtTotalFasilitas = txtTotalFasilitas;
        this.days = days;
        setLocationRelativeTo(null);
        
        fasilitasController.readData(tableFasilitas);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFasilitas = new javax.swing.JTable();
        buttonPanel = new javax.swing.JPanel();
        btnPilih = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Pilih Fasilitas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tableFasilitas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableFasilitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pilih", "Kode Fasilitas", "Fasilitas", "Harga", "Status", "Stok", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFasilitas.setColumnSelectionAllowed(true);
        tableFasilitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableFasilitasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableFasilitas);
        tableFasilitas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tableFasilitas.getColumnModel().getColumnCount() > 0) {
            tableFasilitas.getColumnModel().getColumn(0).setResizable(false);
            tableFasilitas.getColumnModel().getColumn(0).setPreferredWidth(10);
            tableFasilitas.getColumnModel().getColumn(4).setResizable(false);
            tableFasilitas.getColumnModel().getColumn(4).setPreferredWidth(50);
            tableFasilitas.getColumnModel().getColumn(5).setResizable(false);
            tableFasilitas.getColumnModel().getColumn(5).setPreferredWidth(20);
            tableFasilitas.getColumnModel().getColumn(6).setResizable(false);
            tableFasilitas.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
            .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tablePanelLayout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
            .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tablePanelLayout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        buttonPanel.setLayout(new java.awt.GridLayout(1, 0));

        btnPilih.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPilih.setText("Pilih");
        btnPilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihActionPerformed(evt);
            }
        });
        buttonPanel.add(btnPilih);

        btnBatal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBatal.setText("Batal");
        buttonPanel.add(btnBatal);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(0, 485, Short.MAX_VALUE)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 25, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableFasilitasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFasilitasMousePressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_tableFasilitasMousePressed

    private void btnPilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihActionPerformed
        // TODO add your handling code here:
        boolean valid = false;
        for(int i = 0; i < tableFasilitas.getRowCount(); i++){
            if(tableFasilitas.getValueAt(i, 0) != null){
                Boolean  pilih =  Boolean.valueOf(tableFasilitas.getValueAt(i, 0).toString());
               
                if(pilih){
                    String kd_fasilitas = tableFasilitas.getValueAt(i, 1).toString();
                    String nama_fasilitas = tableFasilitas.getValueAt(i, 2).toString();
                    String harga = tableFasilitas.getValueAt(i, 3).toString();
                    String status = tableFasilitas.getValueAt(i, 4).toString();
                    int jml = Integer.parseInt(tableFasilitas.getValueAt(i, 6).toString());
                    int stok = Integer.parseInt(tableFasilitas.getValueAt(i, 5).toString());
                    if(stok > 0 ){
                        Fasilitas fasilitas = new Fasilitas();
                        fasilitas.setKd_fasilitas(kd_fasilitas);
                        fasilitas.setNama(nama_fasilitas);
                        fasilitas.setHarga(harga);
                        fasilitas.setStatus(status);
                        fasilitas.setJumlah_fasilitas(jml);
                        fasilitas.setStok(stok);
                        listFasilitas.add(fasilitas);
                        valid =true;
                    }else{
                        listFasilitas.clear();
                        valid =false;
                        JOptionPane.showMessageDialog(null, "Stok kosong! Tidak dapat memilih fasilitas "+nama_fasilitas, "Kesalahan", JOptionPane.ERROR_MESSAGE);
                    }
                   
                }
            }
        }
        if(valid){
            dispose();
        }
        
    }//GEN-LAST:event_btnPilihActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        DefaultTableModel tableFasModel = (DefaultTableModel)tableFas.getModel();
        if(!listFasilitas.isEmpty()){
            tableFasModel.setRowCount(0);
            int total = 0;
            int no = 0;
            for(Fasilitas fasilitas : listFasilitas){
                int totalHarga = Integer.parseInt(fasilitas.getHarga())*fasilitas.getJumlah_fasilitas()*days;
                total += totalHarga;
                no++;
                Object[] obj = {no,fasilitas.getNama(),"Rp. "+format.format(Integer.parseInt(fasilitas.getHarga())),fasilitas.getStatus(),fasilitas.getJumlah_fasilitas(),"Rp. "+format.format(totalHarga)};
                tableFasModel.addRow(obj);
            }
            txtTotalFasilitas.setText("Rp. "+format.format(total));
        }
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnPilih;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable tableFasilitas;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables
}
