/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengguna.view;

import admin.view.*;
import admin.model.User;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pengguna.controller.InstansiController;
import common.model.PesanDialog;
import javax.swing.JTable;

/**
 *
 * @author WILDAN
 */
public class FormDaftarInstansi extends javax.swing.JInternalFrame {
    private final PesanDialog pesanDialog = new PesanDialog();
    private final InstansiController instansiController = new InstansiController();
    String kd_fasilitas;
    String aktif;
    /**
     * Creates new form FormDaftarInstansi
     */
    public FormDaftarInstansi() {
        initComponents();
        setVisible(true);
        setLocation(0,0);
        instansiController.readData(tableTransaksi);
    }
    
     public JTable getTable() {
        return tableTransaksi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();

        setTitle("Form Daftar Instansi");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Cari");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(975, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 965;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel2, gridBagConstraints);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        tableTransaksi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Detail", "Kode Instansi", "Instansi", "Penanggung Jawab", "Alamat", "No Telepon", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTransaksi.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableTransaksi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableTransaksiMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableTransaksi);
        if (tableTransaksi.getColumnModel().getColumnCount() > 0) {
            tableTransaksi.getColumnModel().getColumn(0).setPreferredWidth(70);
            tableTransaksi.getColumnModel().getColumn(1).setPreferredWidth(100);
            tableTransaksi.getColumnModel().getColumn(2).setPreferredWidth(200);
            tableTransaksi.getColumnModel().getColumn(3).setPreferredWidth(200);
            tableTransaksi.getColumnModel().getColumn(4).setPreferredWidth(200);
            tableTransaksi.getColumnModel().getColumn(5).setPreferredWidth(200);
            tableTransaksi.getColumnModel().getColumn(6).setPreferredWidth(200);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1190;
        gridBagConstraints.ipady = 500;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
        instansiController.readData(tableTransaksi);
    }//GEN-LAST:event_formFocusLost

    private void tableTransaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiMousePressed
        // TODO add your handling code here:
        if(tableTransaksi.getSelectedRow()>= 0){
            kd_fasilitas = tableTransaksi.getValueAt(tableTransaksi.getSelectedRow(), 0).toString();
            aktif = tableTransaksi.getValueAt(tableTransaksi.getSelectedRow(), 4).toString();
            if(aktif.equals("T") || aktif.equals("")){
                aktif = "Y";
            }else{
                aktif = "T";
            }
        }
    }//GEN-LAST:event_tableTransaksiMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tableTransaksi;
    // End of variables declaration//GEN-END:variables
}
