/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pengguna.view;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.io.FileUtils;
import pengguna.controller.FotoController;

/**
 *
 * @author WILDAN
 */
public class UploadFoto extends javax.swing.JDialog {
    File file;
    JFileChooser jfc;
    String kd_instansi;
    String kd_foto="";
    FotoController fotoController = new FotoController();
    String nama_file;
    /**
     * Creates new form UploadFoto
     */
    public UploadFoto(java.awt.Frame parent, boolean modal, String kd_instansi) {
        super(parent, modal);
        this.kd_instansi = kd_instansi;
        initComponents();
        setLocationRelativeTo(null);
        fotoController.readData(tableFoto, kd_instansi);
        
    }
    
    private void clear(){
        lblFoto.setIcon(null);
        lblNamaFile.setText("");
        txtJudul.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableFoto = new javax.swing.JTable();
        lblNamaFile = new javax.swing.JLabel();
        lblFoto = new javax.swing.JLabel();
        btnPilihGambar = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtJudul = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kelola Gambar");
        setResizable(false);

        tableFoto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Foto", "Judul", "Nama File"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableFotoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableFoto);

        lblNamaFile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblNamaFile.setText("Nama File");

        btnPilihGambar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPilihGambar.setText("Pilih Gambar");
        btnPilihGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihGambarActionPerformed(evt);
            }
        });

        btnSimpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setEnabled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setEnabled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        txtJudul.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPilihGambar)
                        .addGap(28, 28, 28)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(lblNamaFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtJudul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNamaFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnHapus)
                            .addComponent(btnPilihGambar))
                        .addGap(0, 5, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPilihGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihGambarActionPerformed
        // TODO add your handling code here:
        jfc=new JFileChooser();
        jfc.setFileFilter(new FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg"));
        if(jfc.showOpenDialog(lblFoto)==JFileChooser.APPROVE_OPTION){
            
            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image image=toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imagedResized=image.getScaledInstance(377, 277, Image.SCALE_DEFAULT);
            ImageIcon imageIcon=new ImageIcon(imagedResized);
            
            lblFoto.setIcon(imageIcon);
            lblNamaFile.setText(jfc.getSelectedFile().getName());
            
            file=new File(jfc.getSelectedFile().getPath());
            btnSimpan.setEnabled(true);
        }
    }//GEN-LAST:event_btnPilihGambarActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(!txtJudul.getText().isEmpty()){
                if(fotoController.simpan("tambah", lblNamaFile, txtJudul, file, kd_instansi)){
                    try {
                        String path=new File(".").getCanonicalPath();
                        FileUtils.copyFileToDirectory(file, new File(path+"/image/"+kd_instansi));
                    } catch (IOException ex) {
                        Logger.getLogger(UploadFoto.class.getName()).log(Level.SEVERE, null, ex);
                    }
                fotoController.readData(tableFoto, kd_instansi);
                clear();
                btnSimpan.setEnabled(false);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Silahkan tambahkan judul foto!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if(!kd_foto.equals("")){
            fotoController.hapus(kd_foto, nama_file, kd_instansi);
            fotoController.readData(tableFoto, kd_instansi);
            clear();
            btnHapus.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(null, "Silahkan pilih foto dari tabel yang akan dihapus!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tableFotoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFotoMousePressed
        // TODO add your handling code here:
        try {
            btnHapus.setEnabled(true);
            btnSimpan.setEnabled(false);
            Toolkit toolkit=Toolkit.getDefaultToolkit();
            int selectedRow = tableFoto.getSelectedRow();
            kd_foto =tableFoto.getValueAt(selectedRow, 0).toString();
            String path=new File(".").getCanonicalPath();
            nama_file=tableFoto.getValueAt(selectedRow, 2).toString();
            Image image=toolkit.getImage(path+"/image/"+kd_instansi+"/"+nama_file);
            Image imagedResized=image.getScaledInstance(377, 277, Image.SCALE_DEFAULT);
            ImageIcon icon=new ImageIcon(imagedResized);
            lblFoto.setIcon(icon);
            txtJudul.setText(tableFoto.getValueAt(selectedRow, 1).toString());
        } catch (IOException ex) {
            Logger.getLogger(UploadFoto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tableFotoMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnPilihGambar;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNamaFile;
    private javax.swing.JTable tableFoto;
    private javax.swing.JTextField txtJudul;
    // End of variables declaration//GEN-END:variables
}
