/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.view;

import admin.controller.FasilitasController;
import admin.model.User;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import common.model.PesanDialog;
import javax.swing.JTable;

/**
 *
 * @author WILDAN
 */
public class FormDaftarFasilitas extends javax.swing.JInternalFrame {
    private final PesanDialog pesanDialog = new PesanDialog();
    private FormUpdateFasilitas formUpdateFasilitas;
    private final FasilitasController fasilitasController = new FasilitasController();
    String kd_fasilitas;
    String aktif;
    /**
     * Creates new form FormKelolaPengguna
     */
    public FormDaftarFasilitas() {
        initComponents();
        setVisible(true);
        
        setLocation(0,0);
        btnAktif.setEnabled(false);
        fasilitasController.readData(tableFasilitas);
    }
    
     public JTable getTable() {
        return tableFasilitas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tableFasilitas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnAktif = new javax.swing.JButton();

        setTitle("Form Daftar Fasilitas");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tableFasilitas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableFasilitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Fasilitas", "Fasilitas", "Harga", "Status", "Stok", "Aktif", "Perubahan Terakhir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableFasilitas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableFasilitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableFasilitasMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableFasilitas);
        if (tableFasilitas.getColumnModel().getColumnCount() > 0) {
            tableFasilitas.getColumnModel().getColumn(0).setPreferredWidth(150);
            tableFasilitas.getColumnModel().getColumn(1).setPreferredWidth(200);
            tableFasilitas.getColumnModel().getColumn(2).setPreferredWidth(200);
            tableFasilitas.getColumnModel().getColumn(3).setPreferredWidth(150);
            tableFasilitas.getColumnModel().getColumn(4).setPreferredWidth(100);
            tableFasilitas.getColumnModel().getColumn(5).setPreferredWidth(150);
            tableFasilitas.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 932;
        gridBagConstraints.ipady = 503;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnUbah.setBackground(new java.awt.Color(0, 204, 0));
        btnUbah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel1.add(btnUbah);

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus);

        btnAktif.setBackground(new java.awt.Color(0, 0, 255));
        btnAktif.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAktif.setForeground(new java.awt.Color(255, 255, 255));
        btnAktif.setText("Aktif");
        btnAktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAktifActionPerformed(evt);
            }
        });
        jPanel1.add(btnAktif);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 1000;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
        fasilitasController.readData(tableFasilitas);
    }//GEN-LAST:event_formFocusLost

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if(tableFasilitas.getSelectedRow()>=0){
            if(pesanDialog.tampilkanPilihan("Apakah anda yakin ingin menghapus?","Konfirmasi", new Object[]{"Ya","Tidak"}) == 0){
                fasilitasController.hapus(kd_fasilitas);
                fasilitasController.readData(tableFasilitas);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Silahkan pilih fasilitas untuk dihapus");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnAktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAktifActionPerformed
        // TODO add your handling code here:
        if(tableFasilitas.getSelectedRow()>=0){
            if(aktif.equals("Y")){
                if(pesanDialog.tampilkanPilihan("Apakah anda yakin ingin mengaktifkan?","Konfirmasi", new Object[]{"Ya","Tidak"}) == 0){
                    fasilitasController.aktif(kd_fasilitas, aktif);
                    fasilitasController.readData(tableFasilitas);
                }
            }else{
                if(pesanDialog.tampilkanPilihan("Apakah anda yakin ingin menonaktifkan?","Konfirmasi", new Object[]{"Ya","Tidak"}) == 0){
                    fasilitasController.aktif(kd_fasilitas, aktif);
                    fasilitasController.readData(tableFasilitas);
                }
            }
            btnAktif.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(this, "Silahkan pilih fasilitas untuk diaktifkan");
        }
    }//GEN-LAST:event_btnAktifActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        if(tableFasilitas.getSelectedRow() >= 0){
            this.formUpdateFasilitas = new FormUpdateFasilitas(null, true, tableFasilitas, kd_fasilitas);
            this.formUpdateFasilitas.setVisible(true);
        }else
            JOptionPane.showMessageDialog(this, "Silahkan pilih fasilitas untuk diperbaharui");
    }//GEN-LAST:event_btnUbahActionPerformed

    private void tableFasilitasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFasilitasMousePressed
        // TODO add your handling code here:
        if(tableFasilitas.getSelectedRow()>= 0){
            btnAktif.setEnabled(true);
            kd_fasilitas = tableFasilitas.getValueAt(tableFasilitas.getSelectedRow(), 0).toString();
            aktif = tableFasilitas.getValueAt(tableFasilitas.getSelectedRow(), 5).toString();
            if(aktif.equals("T") || aktif.equals("")){
                aktif = "Y";
                btnAktif.setText("Aktif");
            }else{
                aktif = "T";
                btnAktif.setText("Non Aktif");
            }
        }
    }//GEN-LAST:event_tableFasilitasMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAktif;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableFasilitas;
    // End of variables declaration//GEN-END:variables
}
