/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin.view;

import admin.controller.GolonganController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import common.model.PesanDialog;
import javax.swing.JTable;

/**
 *
 * @author WILDAN
 */
public class FormDaftarGolongan extends javax.swing.JInternalFrame {
    private final PesanDialog pesanDialog = new PesanDialog();
    private FormUpdateGolongan formUpdateGolongan;
    private final GolonganController golonganController = new GolonganController();
    String kd_golongan;
    /**
     * Creates new form FormKelolaPengguna
     */
    public FormDaftarGolongan() {
        initComponents();
        setVisible(true);
        
        setLocation(0,0);
        golonganController.readData(tableGolongan);
    }
    
     public JTable getTable() {
        return tableGolongan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tableGolongan = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setTitle("Form Daftar Golongan");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tableGolongan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableGolongan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Golongan", "Golongan", "Harga", "Perubahan Terakhir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableGolongan.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableGolongan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableGolonganMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableGolonganMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableGolongan);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 932;
        gridBagConstraints.ipady = 503;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnUbah.setBackground(new java.awt.Color(0, 204, 0));
        btnUbah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel1.add(btnUbah);

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 1000;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
        golonganController.readData(tableGolongan);
    }//GEN-LAST:event_formFocusLost

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if(tableGolongan.getSelectedRow()>=0){
            if(pesanDialog.tampilkanPilihan("Apakah anda yakin ingin menghapus?","Konfirmasi", new Object[]{"Ya","Tidak"}) == 0){
                golonganController.hapus(kd_golongan);
                golonganController.readData(tableGolongan);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Silahkan pilih golongan untuk dihapus");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tableGolonganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableGolonganMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tableGolonganMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        if(tableGolongan.getSelectedRow() >= 0){
            this.formUpdateGolongan = new FormUpdateGolongan(null, true, tableGolongan, kd_golongan);
            this.formUpdateGolongan.setVisible(true);
        }else
            JOptionPane.showMessageDialog(this, "Silahkan pilih golongan untuk diperbaharui");
    }//GEN-LAST:event_btnUbahActionPerformed

    private void tableGolonganMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableGolonganMousePressed
        // TODO add your handling code here:
        if(tableGolongan.getSelectedRow()>=0){
            kd_golongan = tableGolongan.getValueAt(tableGolongan.getSelectedRow(), 0).toString();
        }
    }//GEN-LAST:event_tableGolonganMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableGolongan;
    // End of variables declaration//GEN-END:variables
}
